ERROR - 2023-02-13 04:03:47 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'inventaris_smal...', 3306, '', 0)
#1 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1686): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\Model.php(605): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\kodingan\inventaris\app\Controllers\Umum.php(25): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Umum->index()
#7 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Umum))
#8 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\kodingan\inventaris\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1686): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\Model.php(605): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#4 C:\xampp\htdocs\kodingan\inventaris\app\Controllers\Umum.php(25): CodeIgniter\Model->countAllResults()
#5 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Umum->index()
#6 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Umum))
#7 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\kodingan\inventaris\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\kodingan\inventaris\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-02-13 04:03:47 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1686): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `piala`', [], false)
 3 SYSTEMPATH\Model.php(605): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 4 APPPATH\Controllers\Umum.php(25): CodeIgniter\Model->countAllResults()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Umum->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Umum))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
INFO - 2023-02-13 04:03:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 04:03:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 04:04:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 04:04:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 04:20:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-02-13 09:01:38 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'inventaris_smal...', 3306, '', 0)
#1 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1686): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\Model.php(605): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\inventaris\app\Controllers\Umum.php(25): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Umum->index()
#7 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Umum))
#8 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\inventaris\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1686): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\Model.php(605): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#4 C:\xampp\htdocs\inventaris\app\Controllers\Umum.php(25): CodeIgniter\Model->countAllResults()
#5 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Umum->index()
#6 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Umum))
#7 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\inventaris\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\inventaris\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-02-13 09:01:38 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1686): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `piala`', [], false)
 3 SYSTEMPATH\Model.php(605): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 4 APPPATH\Controllers\Umum.php(25): CodeIgniter\Model->countAllResults()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Umum->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Umum))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-13 13:14:20 --> Cannot redeclare App\Controllers\Umum::xiimipa8papanTulis()
in APPPATH\Controllers\Umum.php on line 3220.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-02-13 13:14:24 --> Cannot redeclare App\Controllers\Umum::xiimipa8papanTulis()
in APPPATH\Controllers\Umum.php on line 3220.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-02-13 13:14:25 --> Cannot redeclare App\Controllers\Umum::xiimipa8papanTulis()
in APPPATH\Controllers\Umum.php on line 3220.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-02-13 16:30:22 --> Cannot redeclare App\Controllers\Umum::xiimipa8papanTulis()
in APPPATH\Controllers\Umum.php on line 3220.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-02-13 16:35:49 --> Cannot redeclare App\Controllers\Umum::aulakursi()
in APPPATH\Controllers\Umum.php on line 3228.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
